name: Create a comment on new issues

on: 
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: |
            A new issue has been created **Markdown** :sparkles:
